# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 等等,我还没想好
email: p_qp__q@163.com
description: > # this means to ignore newlines until "baseurl:"
    等等,我还没想好. P.S. 怎么这么多东西要写..
baseurl: ""
url: "http://pp-qq.github.io/" # the base hostname & protocol for your site
github_username:  pp-qq

# Build settings
markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: "p_qp__q@163.com"
