paginate: 10
gems: [jekyll-paginate]

markdown: redcarpet

# 作者信息
author: 
  name: pp-qq
  email: p_qp__q@163.com
  github: http://github.com/pp-qq
  linkedin: https://www.linkedin.com/in/%E4%BC%9F-%E7%8E%8B-676a4b109

# 站点信息
title: 暂且就叫博客吧
description: 怎么辣么多要我填的!这个是显示在哪的?
url: http://pp-qq.github.io
#url: http://localhost:4000


gavatar: /assets/head.jpg
favicon: /assets/head.jpg

# disqus 设置
disqus:
  shortname: pqpq


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

redcarpet:
    extensions: ["fenced_code_blocks"]


defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: "p_qp__q@163.com"
  
  
