encoding: UTF-8

# Site settings
title: 暂且就叫博客吧
SEOTitle: 暂且就叫博客吧
# header-img: img/home-bg.jpg
email: w@hidva.com
# description: "没有描述"
# keyword: ""
url: "https://blog.hidva.com"              # your host, for absolute URL
# baseurl: "/huxblog-boilerplate"         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
github_username: hidva
linkedin_username: hidva
#twitter_username:  huxpro
# facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 13
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate, jekyll-mermaid]

mermaid:
  src: '/js/mermaid/current/mermaid.min.js'


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings. 多说已经被下线了.
# duoshuo_username: pp-qq
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: '1458dda4af6cd623aa273e7c393be718'
# Google Analytics
# ga_track_id: 'UA-83419943-1'            # Format: UA-xxxxxx-xx
# ga_domain: 'auto'



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "简洁, 高效, 赏心悦目"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "不要点",
        href: "https://www.baidu.com/"
    },
    {
        title: "Go!Go!Go!",
        href: "https://go.hidva.com/"
    },
    {
        title: "这里面真没有啥的",
        href: "/private%3f/"
    }
]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "w@hidva.com"
      catalog: true


